### ISSUE TITLE
app-func-sdk-go is not up-to-date in go.mod

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/app-service-configurable#107]
We are testing V2 APIs, but they are not available in the latest image.
We found out the reason is that app-func-sdk-go stopped tagging after July 31st, and app-service-configurable is still using 
https://github.com/edgexfoundry/app-functions-sdk-go/tree/v1.2.1-dev.17

All the new changes in August are not included into the current app-service-configurable image.

**Comment by lenny-intel** [comment]
Apparently, all of the `master` builds in the pipeline  have been failing the `publish Swagger` step so no new tags have been generated. Will work with @ernestojeda to resolve.
