### ISSUE TITLE
Sample configuration under res/mqtt-export still uses deprecated MQTTSend

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/app-service-configurable#108]
Per https://docs.edgexfoundry.org/1.2/microservices/application/AppServiceConfigurable/#mqttsend, MQTTSend has been deprecated and the community suggests to use MQTTSecretSend.  However, the sample configuration under res/mqtt-export still uses MQTTSend.  The community shall consider to update the sample configuration to use MQTTSecretSend.

**Comment by lenny-intel** [comment]
@judehung ,  We specific didn't change the profile to use the new MqttSecretSend since IMHO, it would be a breaking change. We did add the MqttSecretSend to the profile configuration so user could configure and use it. @rsdmike , @jpwhitemn , Thoughts on this?

**Comment by cloudxxx8** [comment]
The race condition issue is only fixed in MQTTSecretSend, so we need this change for the automatic performance test
https://github.com/edgexfoundry/app-functions-sdk-go/pull/474

**Comment by cloudxxx8** [comment]
Sorry, I just noticed it has been fixed in MQTTSend, too.
