### ISSUE TITLE
How to handle the incoming MQTT packets with the same MQTT connection to the mqttexport 

### ISSUE THREAD

**Issue by wallace-hu** [edgexfoundry/app-service-configurable#307]
Hi dear:
      Now i can use the app-serivce-configurable application connected and published packets to the MQTT server with below setting in the .toml file:

      [Writable.Pipeline.Functions.MQTTSend.Addressable]
        Address=   "192.168.34.127"
        Port=      1883
        Protocol=  "tcp"
        Publisher= "client_id_xxxxxxx"
        User=      "lf_user"
        Password=  "lf_pwd"
        Topic=     "iot-report"

I have a problem,   Where can i subscribe the reponse MQTT packets if the MQTT server had response?  

Thank you

**Comment by lenny-intel** [comment]
The built in MQTT Export doesn't not have subscribe capability for responses. 
You could create a custom App Service using the App SDK that adds this capability for your use case.

**Comment by lenny-intel** [comment]
answered
