### ISSUE TITLE
Can't run App services while executing random number application

### ISSUE THREAD

**Issue by Rakshithakrishna2** [edgexfoundry/app-service-configurable#315]
Started to use Ireland version (2.0.0) of EdgeX with 2.0.1 version of App service configurable file,
Want to execute random number generation, for that don't want security components, to do such I have commented few lines in configuration file of mqtt export, the edited configuration file is attached below in images format, please find.

Now after executing it, getting errors as show below

rakshitha@xxx:~/Ireland/app-service-configurable$ ./app-service-configurable 
level=INFO ts=2021-08-30T05:47:05.419073952Z app=app- source=secret.go:59 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-08-30T05:47:05.419213275Z app=app- source=secret.go:71 msg="Attempting to create secret client"
level=WARN ts=2021-08-30T05:47:05.419274678Z app=app- source=secret.go:81 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=ERROR ts=2021-08-30T05:47:06.419771053Z app=app- source=bootstrap.go:46 msg="failed to create SecretProvider: unable to create SecretClient: invalid secrets client type of ''"

![Screenshot from 2021-08-30 11-26-56](https://user-images.githubusercontent.com/88701371/131292147-6340fc85-b0a8-4be2-b1f1-17c4b006daef.png)
![Screenshot from 2021-08-30 11-27-14](https://user-images.githubusercontent.com/88701371/131292188-aa6ff34f-e81b-4a29-98f9-940789b1edee.png)
![Screenshot from 2021-08-30 11-27-35](https://user-images.githubusercontent.com/88701371/131292208-845d34b9-de05-41a4-9384-411989c666f7.png)

**Comment by lenny-intel** [comment]
Please don't submit issue for same questions you have asked in slack. Same people are see both. Slack is best for questions.
