### ISSUE TITLE
Store and forward after MQTT network connect loss doesn't work

### ISSUE THREAD

**Issue by wallace-hu** [edgexfoundry/app-service-configurable#318]
I have seen the "store and forward"  feature in the toml file ,   Was it also designed to implementing  the feature of  “store and forward after a network connect loss”?  For example,  In some scenarios, We need store the datas when the network lost connected, and after some time the network recovered, The application can forward the stored datas to the cloud side. 

B.R
Thank you.

**Comment by wallace-hu** [comment]
> @wallace-hu , yes this exactly what is is designed for.
> https://docs.edgexfoundry.org/2.0/microservices/application/AdvancedTopics/#store-and-forward
Thanks for the Info,   I have done a test to verify this feature as below:
1. Download the edgex-go v2.0 and run it on my Ubuntu system.
2. Download and run  app-service-configurable(version 2.0.0).  In the  app-service-configurable configuration, I enable the "store and forward" as below:
 [Writable.StoreAndForward]
  Enabled = true
  RetryInterval = "5s"
  MaxRetryCount = 10
other settings are default.
3. Download and run edgex\device-sdk-c  example (https://github.com/edgexfoundry/device-sdk-c/tree/main/src/c/examples/random)to provide device service datas.
4. As the  app-service-configurable default connect to local broker. I installed a Mosquitto in my Ubuntu and subscribe the events from the  app-service-configurable MQTT-export packets to observer them.
5 If i stop the mosquitto service and then restart it.  The  app-service-configurable will report connection failure and then connected OK.  In this time the device service application still had data send to the message bus,  Why  I didn't find these  packets between the time the broker stopped and restarted were re-send after the app-service-configurable  connected to the broker again. 

![image](https://user-images.githubusercontent.com/74388179/133545613-d59b3cc0-036e-4e29-8747-004f63b37e0e.png)

Is there any additional action that i need do?

**Comment by lenny-intel** [comment]
This is because the once the initial broker connection is made the `paho.mqtt.golang` doesn't return an error when publishing when the broker is stopped and the `IsConnected()` function returns true. :-(

Here is the issue we are dealing with.
https://stackoverflow.com/questions/28125959/paho-mqtt-client-behaviour-when-broker-times-out-client-disconnects

Try setting QOS=2 to see if the Paho client reties the messages when broker reconnects.

**Comment by lenny-intel** [comment]
Also try setting `retain=true` . If this doesn't resolve the issue please submit a bug for Store and Forward with MQTT Export. THX!

**Comment by wallace-hu** [comment]
> @wallace-hu did you get this to work with suggestions above?
Still not, The action is still under doing,  I have another problem with edgex-go 2.0 services when running the test again for unknow reason which caused the app-service-configurable application cannot run up for the secrets token reason. I have resolved it first.  

Please kindly waiting my update

**Comment by wallace-hu** [comment]
Update:
    Looks like the setting "retain=true“  and "Qos=2" dont caused any changes.
Pls refer to below log,  device service report "Value=`89`"/"Value=`90`" /"Value=`91`"  events,  When "Value=`92`" the remote broker service  was closed manually, so  "Value=`92`"/"Value=`93`" /"Value=`94`"  events was failed to send to the broker,   Then I start up the mosquitto broker manually, So "Value=`95`"/"Value=`96`" /"Value=`97`"  events was successfully send to the remote broker, While the app-service-configuable show "msg="0 stored data items found for retrying", Was it expected that 3(92/93/94 events) stored data were found for retrying?


level=DEBUG ts=2021-11-01T12:41:57.336143492Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:41:57.336200828Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:41:57.336234259Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:41:57.336322825Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:41:57.336358198Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:41:57.336388152Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:41:57.336497046Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`89`"
level=DEBUG ts=2021-11-01T12:41:57.336531716Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:41:57.336600488Z app=app- source=mqttsecret.go:203 msg="Sent data to MQTT Broker in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:42:07.336502314Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:42:07.336605244Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:42:07.336736117Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:42:07.336774619Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:42:07.336808145Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:07.336904767Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:07.336941532Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:42:07.336972183Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:42:07.337002935Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`90`"
level=DEBUG ts=2021-11-01T12:42:07.337036108Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:42:07.33711121Z app=app- source=mqttsecret.go:203 msg="Sent data to MQTT Broker in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:42:13.002564934Z app=app- source=storeforward.go:144 msg="0 stored data items found for retrying"
level=DEBUG ts=2021-11-01T12:42:17.335995744Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:42:17.336099556Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:42:17.336164047Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:42:17.336461515Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:42:17.33673139Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:17.336952698Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:17.336966262Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:42:17.33697431Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:42:17.336982629Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`91`"
level=DEBUG ts=2021-11-01T12:42:17.336992674Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=INFO ts=2021-11-01T12:42:17.337009526Z app=app- source=mqttsecret.go:151 msg="Connecting to mqtt server for export"
level=ERROR ts=2021-11-01T12:42:17.337308587Z app=app- source=runtime.go:247 msg="Pipeline (default-pipeline) function #1 resulted in error: in pipeline 'default-pipeline', could not connect to mqtt server for export, dropping event. Error: network Error : dial tcp 127.0.0.1:1883: connect: connection refused (X-Correlation-ID=80342217-996c-459a-a5bf-2f148088c504)"
level=DEBUG ts=2021-11-01T12:42:27.336216668Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:42:27.336283358Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:42:27.336619379Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:42:27.336684588Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:42:27.336719028Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:27.336805581Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:27.336841389Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:42:27.336879261Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:42:27.336912067Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`92`"
level=DEBUG ts=2021-11-01T12:42:27.336944235Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=INFO ts=2021-11-01T12:42:27.336982Z app=app- source=mqttsecret.go:151 msg="Connecting to mqtt server for export"
level=ERROR ts=2021-11-01T12:42:27.337158473Z app=app- source=runtime.go:247 msg="Pipeline (default-pipeline) function #1 resulted in error: in pipeline 'default-pipeline', could not connect to mqtt server for export, dropping event. Error: network Error : dial tcp 127.0.0.1:1883: connect: connection refused (X-Correlation-ID=3564f77d-176a-4fcb-801f-5df3fd5977c2)"
level=DEBUG ts=2021-11-01T12:42:37.336320787Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:42:37.336402268Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:42:37.336656892Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:42:37.336720262Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:42:37.336754797Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:37.336852321Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:37.336888238Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:42:37.336917864Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:42:37.336947474Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`93`"
level=DEBUG ts=2021-11-01T12:42:37.336978995Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=INFO ts=2021-11-01T12:42:37.337017225Z app=app- source=mqttsecret.go:151 msg="Connecting to mqtt server for export"
level=ERROR ts=2021-11-01T12:42:37.337170513Z app=app- source=runtime.go:247 msg="Pipeline (default-pipeline) function #1 resulted in error: in pipeline 'default-pipeline', could not connect to mqtt server for export, dropping event. Error: network Error : dial tcp 127.0.0.1:1883: connect: connection refused (X-Correlation-ID=2f75b9e6-7414-4f72-94f3-af10aebadc08)"
level=DEBUG ts=2021-11-01T12:42:47.336430424Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:42:47.336512365Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:42:47.336577916Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:42:47.336798144Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:42:47.336869491Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:47.337072259Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:47.33712826Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:42:47.337160049Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:42:47.337190733Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`94`"
level=DEBUG ts=2021-11-01T12:42:47.337223958Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=INFO ts=2021-11-01T12:42:47.337262363Z app=app- source=mqttsecret.go:151 msg="Connecting to mqtt server for export"
level=ERROR ts=2021-11-01T12:42:47.337461658Z app=app- source=runtime.go:247 msg="Pipeline (default-pipeline) function #1 resulted in error: in pipeline 'default-pipeline', could not connect to mqtt server for export, dropping event. Error: network Error : dial tcp 127.0.0.1:1883: connect: connection refused (X-Correlation-ID=3f54af7a-fe01-4699-aa37-85ce881a78ba)"
level=DEBUG ts=2021-11-01T12:42:57.336826153Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:42:57.337223382Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:42:57.337265151Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:42:57.33733078Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:42:57.337366407Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:57.337441123Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:42:57.337476428Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:42:57.337507466Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:42:57.337538315Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`95`"
level=DEBUG ts=2021-11-01T12:42:57.337570814Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=INFO ts=2021-11-01T12:42:57.337609474Z app=app- source=mqttsecret.go:151 msg="Connecting to mqtt server for export"
level=INFO ts=2021-11-01T12:42:57.337939165Z app=app- source=mqttsecret.go:160 msg="Connected to mqtt server for export in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:42:57.337995021Z app=app- source=mqttsecret.go:203 msg="Sent data to MQTT Broker in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:43:07.337071939Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:43:07.3373271Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:43:07.337392977Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:43:07.337429346Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:43:07.337461391Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:43:07.337554031Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:43:07.337589323Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:43:07.337619197Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:43:07.337654828Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`96`"
level=DEBUG ts=2021-11-01T12:43:07.337688801Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:43:07.337758342Z app=app- source=mqttsecret.go:203 msg="Sent data to MQTT Broker in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:43:13.004619411Z app=app- source=storeforward.go:144 msg="0 stored data items found for retrying"
level=DEBUG ts=2021-11-01T12:43:17.338626177Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:43:17.339323876Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:43:17.339513411Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:43:17.339571774Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:43:17.339583474Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:43:17.33965307Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:43:17.340313061Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:43:17.340323887Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:43:17.340332369Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`97`"
level=DEBUG ts=2021-11-01T12:43:17.34034176Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:43:17.340386703Z app=app- source=mqttsecret.go:203 msg="Sent data to MQTT Broker in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:43:27.338097256Z app=app- source=messaging.go:178 msg="MessageBus Trigger: Received message with 420 bytes on topic 'edgex/events/core/Example-Counter/Counter1/Counter'. Content-Type=application/json"
level=DEBUG ts=2021-11-01T12:43:27.338347174Z app=app- source=messaging.go:185 msg="MessageBus Trigger found 1 pipeline(s) that match the incoming topic 'edgex/events/core/Example-Counter/Counter1/Counter'"
level=DEBUG ts=2021-11-01T12:43:27.338388574Z app=app- source=runtime.go:137 msg="Pipeline 'default-pipeline' processing message 2 Transforms"
level=DEBUG ts=2021-11-01T12:43:27.338400455Z app=app- source=runtime.go:161 msg="Expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-11-01T12:43:27.338410297Z app=app- source=runtime.go:280 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:43:27.338472045Z app=app- source=runtime.go:287 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-11-01T12:43:27.33848316Z app=app- source=runtime.go:338 msg="Event Received with ProfileName=Example-Counter, DeviceName=Counter1 and ReadingCount=1"
level=DEBUG ts=2021-11-01T12:43:27.338490818Z app=app- source=runtime.go:345 msg="Event has no tags"
level=DEBUG ts=2021-11-01T12:43:27.338498711Z app=app- source=runtime.go:358 msg="Reading #1 received with ResourceName=Counter, ValueType=Uint32, Value=`98`"
level=DEBUG ts=2021-11-01T12:43:27.338514689Z app=app- source=conversion.go:67 msg="Transforming to JSON in pipeline 'default-pipeline'"
level=DEBUG ts=2021-11-01T12:43:27.338554002Z app=app- source=mqttsecret.go:203 msg="Sent data to MQTT Broker in pipeline 'default-pipeline'"
^Clevel=INFO ts=2021-11-01T12:43:31.806943517Z app=app- source=service.go:200 msg="Terminating signal received: interrupt"
level=INFO ts=2021-11-01T12:43:31.806973712Z app=app- source=storeforward.go:102 msg="Exiting StoreAndForward Retry Loop"
level=INFO ts=2021-11-01T12:43:31.806993818Z app=app- source=configupdates.go:62 msg="Exiting waiting for App Service configuration updates"
level=INFO ts=2021-11-01T12:43:31.807008593Z app=app- source=messaging.go:123 msg="Exiting waiting for MessageBus 'edgex/events/#' topic messages"
level=INFO ts=2021-11-01T12:43:31.807018248Z app=app- source=telemetry.go:83 msg="Exiting CPU Usage Average loop"
level=INFO ts=2021-11-01T12:43:31.807034438Z app=app- source=messaging.go:139 msg="Exiting waiting for MessageBus errors and background publishing"
level=INFO ts=2021-11-01T12:43:31.807042512Z app=app- source=messaging.go:168 msg="Disconnecting from the message bus"
root@wallace-VirtualBox:/home/edgex/app-service-configurable# ^C
root@wallace-VirtualBox:/home/edgex/app-service-configurable# ^C
root@wallace-VirtualBox:/home/edgex/app-service-configurable#

**Comment by lenny-intel** [comment]
@wallace-hu , thanks for the detailed information. I have re-classified this issue as a bug and will attempt to fix for the up-coming Jakarta release.

**Comment by lenny-intel** [comment]
@wallace-hu , I have addressed this issue. Now the mqtt-export will fail if the connection is not open (different than connected). If persist of failure and store and forward are enabled the failed data will be retied and sent when the connect is re-established.

Please give that latest app-service-configurable a try and verify it works in your use case, THX!

**Comment by wallace-hu** [comment]
> @wallace-hu , I have addressed this issue. Now the mqtt-export will fail if the connection is not open (different than connected). If persist of failure and store and forward are enabled the failed data will be retied and sent when the connect is re-established.
> 
> Please give that latest app-service-configurable a try and verify it works in your use case, THX!
With the latest release, I try the test again, Firstly the apearance keep same as my previous test, Then ckecking into the code, We find that the default setting "PersistOnError" should aslo be set to "true" :
[Writable.Pipeline.Functions.MQTTExport] ---> PersistOnError = "true".

Now with the default setting [Writable.Pipeline.Functions.MQTTExport] PersistOnError = "true". and   [Writable.StoreAndForward]  Enabled = true. 

Then the feature work.

Thanks for your support. 👍
