### ISSUE TITLE
[snap] modify install hook to drop usage of SNAP_INSTANCE_NAME

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/app-service-configurable#32]
The current snap install hook is forced to use the environment variable SNAP_INSTANCE_NAME when it disables the service on install. At the moment this is required as the snapctl command doesn't have the capability to introspect the instance name for service commands. This is slated to be fixed soon, so this bug is a placeholder to revise this install hook and bump the minimum required version of snapd once fixed.

The usage of SNAP_INSTANCE_NAME was introduced by the following PR:

https://github.com/edgexfoundry/app-service-configurable/pull/26

For more details please refer to the following forum post:

https://forum.snapcraft.io/t/run-configure-hook-of-nextcloud-1-snap-run-hook-configure-error-error-running-snapctl-unknown-service-nextcloud-apache/11422/7

**Comment by tonyespy** [comment]
Please assign this to me...

**Comment by lenny-intel** [comment]
@tonyespy , is this still needed?

**Comment by tonyespy** [comment]
Yes, as it hasn't yet been fixed in snapd.

**Comment by lenny-intel** [comment]
Ok, so it needs to be on hold until it is fixed in snapd then?

**Comment by tonyespy** [comment]
The underlying snapd bug hasn't been resolved yet, and the snap works as is, so I'm closing this issue. If/when a fix lands, they'll need to ensure that it's backwards compatible too.
