### ISSUE TITLE
How to push response back to core data 

### ISSUE THREAD

**Issue by gaurav8222** [edgexfoundry/app-service-configurable#440]
Hi,
     I have exported the data using HTTP export and posted the data to my flask API  endpoints (running on a local system) and returned the response from the flask API. How I can push that response (JSON format) in core data back?

Please help in resolving this issue it will be really appreciable.

**Comment by lenny-intel** [comment]
@gaurav8222 , if you want the raw response data available as an EdgeX event/reading then you have to use the deprecated **PushToCore** function: https://docs.edgexfoundry.org/2.2/microservices/application/AppServiceConfigurable/#pushtocore
Problem is this function is not included in the **http-export** profile, but it is included in the **sample** profile which can be configured to do **http-export** via env overrides.
https://github.com/edgexfoundry/app-service-configurable/blob/main/res/sample/configuration.toml#L85

This does exposes a hole in our capability once PushToCore has been removed in the future. I have created an enhancement issue to address this hole: https://github.com/edgexfoundry/app-functions-sdk-go/issues/1149

**Comment by lenny-intel** [comment]
@gaurav8222 did this answer your question? If so., please close this issue.

**Comment by lenny-intel** [comment]
Closing due to no response.
