### ISSUE TITLE
Face Detection On live video streaming WebCam

### ISSUE THREAD

**Issue by gaurav8222** [edgexfoundry/app-service-configurable#443]
Hi,
    I want to do live video streaming and want to detect faces in that live stream. My face detection app running on my local system.
So please can you tell me how we will send the video live stream to edgex foundry and how to return the detected faces on video.

If you can provide a document or any tutorial for this case study it will be really helpful.

**Comment by lenny-intel** [comment]
Live streams never go thru EdgeX, only snap shots and inference results, i.e. from your  `face detection app` 
The Camera Management App Service example shows how to get the live stream URL from an ONVIF Camera and connect it up to Intel's EVAM to do AI/ML processing with OpenVINO modules.
https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management

**Comment by gaurav8222** [comment]
Hi ,
     I found this youtube video link https://youtu.be/z5rEn6D3u3Q 
Video streaming demo through edgex foundry so please can you tell how we can perform same task with jakarta version .
If you can provide the device service and profile for this demo if this is the possible scenarios that can be performed.

**Comment by lenny-intel** [comment]
You will have to contact to owners of that demo for the information you have requested.
Have you looked at the `Camera Management App Service example` above?

**Comment by gaurav8222** [comment]
Hi @lenny-intel I have checked the above link it is really helpful and able to connect the camera usinf onvif.
