### ISSUE TITLE
Service built from app-service-configurable not appear on App Service List on EdgeX UI

### ISSUE THREAD

**Issue by tntthanh** [edgexfoundry/app-service-configurable#456]
Hi everyone,
Please help me on this thing - that I had built service into execute file using this source repo (app-service-configurable), then run. But when examining EdgeX UI on port 4000 at App Service List, I don't see the service appearing on the list, although it operated normally that it had exported data stably and correctly.
Thanh you very much.

**Comment by lenny-intel** [comment]
Duplicate of https://github.com/edgexfoundry/edgex-ui-go/issues/546.
