### ISSUE TITLE
Unable to receive HTTPExportSize metrics

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/app-service-configurable#508]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: app-services

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
This issue still existed after fixing edgexfoundry/app-functions-sdk-go#1266
1. Deploy EdgeX with attached compose file.(For the recreation I used the [TAF sample http server](https://github.com/edgexfoundry/edgex-taf/blob/35e89d7f1374b7c01018ead79fcab654574fdefc/TAF/utils/src/setup/httpd_server.py), If you use your own http server, please modify the compose file for HTTPExport URL parameter)
2. Set app-sample LogLevel to `DEBUG`
3. Set app-sample ExectionOrder to `HTTPExport`
4. Set HTTPExportSize Metrics to `true`
[docker-compose-no-secty-with-app-sample.yml.zip](https://github.com/edgexfoundry/app-functions-sdk-go/files/10544059/docker-compose-no-secty-with-app-sample.yml.zip)

## 🔥 Exception or Error
<pre><code>
After the metrics default interval time(30s), No any didn't receive the metrics for HTTPExportSize.
`Publish 0 metrics to the 'edgex/telemetry/app-sample' base topic` found In app-sample log.
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** x86 / Ubuntu

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@cherrycl , this is because ASC was never updated to use latest SDK with the fix. It has now been updated. Please verify this has been resolved. THX!
