### ISSUE TITLE
Post secret API got error "SecretRequest.Path field is required"

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/app-service-configurable#522]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: app-services

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with app-service functional-test profile
2. Send API
```
POST localhost:59705/api/v2/secret
{
   "apiVersion":"v2",
   "secretName":"aes",
   "secretData":[
      {
         "key":"key",
         "value":"217A24432646294A404E635266556A586E3272357538782F413F442A472D4B6150645367566B59703373367639792442264529482B4D6251655468576D5A7134"
      }
   ]
}

```

## 🔥 Exception or Error
<pre><code>
Response.
{
    "apiVersion": "v2",
    "message": "JSON decode failed",
    "statusCode": 400
}

Logs:
level=ERROR ts=2023-02-21T08:07:45.583079282Z app=app-functional-tests source=controller.go:137 msg="JSON decode failed -> SecretRequest validation failed. -> SecretRequest.Path field is required"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** ubuntu/x86

**EdgeX Version [**REQUIRED**]:**Main

**Anything else relevant?**

**Comment by lenny-intel** [comment]
This is due to the recent change to rename `Path` to `SecretName`

**Comment by cherrycl** [comment]
Fixed.
