### ISSUE TITLE
Add InsecureSecrets section to external-mqtt-trigger profile for testing purpose

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/app-service-configurable#578]
# 🐞 Bug Report

### Description and Minimal Reproduction [**REQUIRED**]
Based on the request of [edgex-taf #848](https://github.com/edgexfoundry/edgex-taf/issues/848), set the authmode of external MQTT to usernamepassword. Add InsecureSecrets to the external-mqtt-trigger profile to connect secure MQTT.

**Comment by lenny-intel** [comment]
@cherrycl , @cloudxxx8 , do you agree this bug is a medium and the work around is to make the changes in #579 manually for 3.0.0? i.e. don't need a patch release for Minnesota?

**Comment by cloudxxx8** [comment]
yes, I agree.  It's quite minor.
Also, the default AuthMode is none.  This change is for TAF to easily config the tests.
