### ISSUE TITLE
MessageBus trigger: Could not publish to topic 'app1-rule-events' for pipeline 'default-pipeline': nats: no response from stream

### ISSUE THREAD

**Issue by edgego** [edgexfoundry/app-service-configurable#587]
# Question

### Affected Services [**REQUIRED**]

 The issue is located in: 

 app service configurable (version v2.3.0)

### Is this a regression?
NO

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
When set edgex messagebus to nats-jetstream, and set pipeline to app service configurable, then got error:

level=ERROR ts=2023-08-21T09:16:47.352212598Z app=app- source=messaging.go:239 msg="MessageBus trigger: Could not publish to topic 'app1-rule-events' for pipeline 'default-pipeline': nats: no response from stream"
level=ERROR ts=2023-08-21T09:16:47.352313369Z app=app- source=triggermessageprocessor.go:191 msg="failed to process output for message '27b943f2-9978-441c-b726-6ac651694e5e' on pipeline default-pipeline: nats: no response from stream"
level=ERROR ts=2023-08-21T09:16:47.352364611Z app=app- source=messaging.go:199 msg="MessageBus Trigger: Failed to process message on pipeline(s): 1 error occurred:\n\t* nats: no response from stream\n\n"
level=ERROR ts=2023-08-21T09:16:48.370327233Z app=app- source=messaging.go:239 msg="MessageBus trigger: Could not publish to topic 'app1-rule-events' for pipeline 'default-pipeline': nats: no response from stream"

app1 messagebus config:

[Trigger]
  Type="edgex-messagebus"
    [Trigger.EdgexMessageBus]
      Type = "nats-jetstream"
      [Trigger.EdgexMessageBus.SubscribeHost]
         Host = "edge-nats-server"
         Port = 4222
         Protocol = "tcp"
         SubscribeTopics="edgex/events/#"
      [Trigger.EdgexMessageBus.PublishHost]
         Host = "edge-nats-server"
         Port = 4222
         Protocol = "tcp"
         PublishTopic="app1-rule-events"
          [Trigger.EdgexMessageBus.Optional]
            authmode = 'usernamepassword'
            secretname = 'redisdb'
            ClientId ="app1"
            Format = "nats"
            ConnectTimeout = "5"
            RetryOnFailedConnect = "true"
            QueueGroup = ""
            Durable = ""
            AutoProvision = "true"
            Deliver = "new"
            DefaultPubRetryAttempts = "2"
            Subject = "edgex/#"

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@edgego , I assume you are using Levski release? 

Have you read the NATs MessageBus section here: https://docs.edgexfoundry.org/2.3/microservices/general/messagebus/#nats
Specifically the part about `Currently services must be specially built with the include_nats_messaging tag to enable this option` ? This applies to all services, not just your App Service and The NATS Server must be running. See deployment section
https://docs.edgexfoundry.org/2.3/microservices/general/messagebus/#docker_1

**Comment by lenny-intel** [comment]
@edgego , in the future please do not post duplicate question here and in discussions. Discussions is the appropriate place for these questions.
