### ISSUE TITLE
Bug with key in consul when changing profiles

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry/app-service-configurable#6]
This might be more of edge case, but running with a profile will correctly populate consule (i.e. docker-rules-engine) but if you remove the profile, then it will continue to use the same key despite the name changing. 

Steps to Reproduce:

1) With consul up and running, Run app service configurable in docker specifying  a profile: `--profile=docker-rules-engine` (i.e using `docker run` or `docker-compose up`)
2) Observe the correct key/values in consul under the correct key of `AppService-docker-rules-engine`
3) Rerun the command without a profile.
4) Observe that no new entry is in Consul and the old key is still being used and observed for changes for the new container.

**Comment by lenny-intel** [comment]
@rsdmike , can you please add the steps to recreate?
