### ISSUE TITLE
Feat: add service start up duration in log

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/app-service-configurable#87]
In other EdgeX services, we can always see the log like:

> Service started in: 2.729020742s

However, app-service-configurable doesn't print this log message.

**Comment by cloudxxx8** [comment]
add @cherrycl for awareness

**Comment by lenny-intel** [comment]
All other service have use the `message` bootstrap handler which logs this information. 
https://github.com/edgexfoundry/edgex-go/blob/a7fc36b9b3e04c465199d9026bf92f5d2cd5f3b5/internal/core/command/main.go#L80
Should be as simple as adding this to the SDK's call to bootstrap.RunAndReturnWaitGroup()
